In [1]:
import numpy as np

In [2]:
y = np.array([5,6,7,8,9,10])

In [3]:
y

array([ 5,  6,  7,  8,  9, 10])

In [4]:
y.dtype

dtype('int32')

In [5]:
z=np.array([6,5,4,3,2,1])
z

array([6, 5, 4, 3, 2, 1])

In [6]:
z=(y+z)/11
z

array([ 1.,  1.,  1.,  1.,  1.,  1.])

In [7]:
r = np.random.random((1,10))
r

array([[ 0.16753192,  0.52151714,  0.07555117,  0.83286735,  0.05344565,
         0.92435799,  0.07081418,  0.64606967,  0.72180416,  0.41952592]])

In [8]:
type(z)

numpy.ndarray

In [9]:
z.dtype

dtype('float64')

In [10]:
type(r)

numpy.ndarray

In [11]:
s = np.random.random((10,2))
s

array([[  2.10663795e-01,   2.83012992e-01],
       [  4.13786267e-02,   1.28493455e-01],
       [  2.91995074e-01,   1.19975557e-01],
       [  7.07812895e-01,   8.81944267e-01],
       [  7.43836566e-02,   2.68451082e-01],
       [  7.19488188e-02,   1.78599471e-01],
       [  2.22904284e-01,   6.63511841e-01],
       [  3.93829556e-01,   8.61262544e-04],
       [  3.46731373e-01,   2.84311387e-01],
       [  6.17436363e-01,   7.46222427e-01]])

In [12]:
type(s)

numpy.ndarray